//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovernCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendar()
        {
            this.CalendarEvents = new HashSet<CalendarEvent>();
        }
    
        public int CalendarId { get; set; }
        public string CalendarName { get; set; }
        public int WebsiteId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Website Website { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarEvent> CalendarEvents { get; set; }
    }
}
